### ISSUE TITLE
improve css

### ISSUE THREAD

**Issue by 5h0bh4nk** [5h0bh4nk/React-TICTAC#1]
The history of game and buttons must be presented in a better way , side by side preferable .

**Comment by Shreelaxmi-M** [comment]
I will do this ,can you assign me?

**Comment by 5h0bh4nk** [comment]
Sure

**Comment by 5h0bh4nk** [comment]
@shree-create i am assigning this issue to you

**Comment by 5h0bh4nk** [comment]
isssue resolved by @shree-create .
